baseURL = 'https://42.tinylinden.eu/'
languageCode = 'en-us'
title = '42'
theme = 'hyde'

[params]
	description = 'the answer to the ultimate question of life, the universe, and everything'
	copyright = ' '
